spring:
  application:
    name: emart-zuul-service
server:
  port: 9002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    securePortEnabled: true
    instance-id: ${spring.application.name}:${server.port}

# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
  endpoint:
    health:
      show-details: ALWAYS

# 网关配置

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false # 停用超时设置
        isolation:
          thread:
            timeoutInMilliseconds: 80000

swagger.enabled: true


apiurl:
  gatewayurl: http://localhost:9002

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    emart-buyer-service:
      path: /emart-buyer-service/**
      serviceId: emart-buyer-service
      stripPrefix: true
      sensitiveHeaders:
    emart-seller-service:
      path: /emart-seller-service/**
      serviceId: emart-seller-service
      stripPrefix: true
      sensitiveHeaders:
    emart-service:
      path: /emart-service/**
      serviceId: emart-service
      stripPrefix: true
      sensitiveHeaders: Cookie,Set-Cookie # Exclude authorization from sensitive headers